FROM bitnami/spark:latest

USER root

RUN apt-get update && apt-get install -y iputils-ping telnet
RUN apt-get update && apt-get install -y wget
RUN apt-get update && apt-get install -y curl
# Copiez le fichier requirements.txt dans le conteneur
COPY requirements.txt /opt/spark-apps/requirements.txt


# Installez les dépendances Python
RUN pip install --no-cache-dir -r /opt/spark-apps/requirements.txt

# Changez l'utilisateur pour spark
USER 1001
